controller_joint_names: ['', 'driving_wheel_left_Joint', 'driving_wheel_right_Joint', 'slaving_wheel_support_left_Joint', 'slaving_wheel_left_Joint', 'slaving_wheel_support_right_Joint', 'slaving_wheel_right_Joint', ]
